apiVersion: eksctl.io/v1alpha5
# eksctl create cluster --config-file ./cluster_config.yaml
# things to change as needed
#     name, region, public and private subnets, nodegroup name, instanceType, publicKeyName, tags
kind: ClusterConfig
metadata:
  name: dev-eks-test
  region: us-east-2
  version: "1.23"

vpc:
  subnets:
    private:
      us-east-2a: { id: subnet-0af5bac796fb5e132 }
      us-east-2b: { id: subnet-0b476d2e1af85eb0a }
      us-east-2c: { id: subnet-06832e538c803d2f0 }
    public:
      us-east-2a: { id: subnet-0b2e48778efee9b51 }
      us-east-2b: { id: subnet-0fc70c7a888898707 }
      us-east-2c: { id: subnet-06654d547f9ad82b9 }

managedNodeGroups:
  - name: test-ng-1
    minSize: 1
    maxSize: 6
    desiredCapacity: 1
    instanceType: t2.medium
    labels: {role: worker}
    ssh:
      publicKeyName: eks-us-east2
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true